### ISSUE TITLE
Crashes at end of qrz

### ISSUE THREAD

**Issue by barjac** [DanielG/aldo#1]
Built with gcc-4.9.2

After sending a block of calls the program crashes with:

Keying speed: 12 wpm
Template callsign: @?#$@@@?
About to start keying. Get ready...
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::substr: __pos (which is 40) > this->size() (which is 38)
Aborted

Running under gdb:

(gdb) bt
#0  0x00007ffff702b627 in raise () from /lib64/libc.so.6
#1  0x00007ffff702cdba in abort () from /lib64/libc.so.6
#2  0x00007ffff7928c0d in __gnu_cxx::__verbose_terminate_handler () at ../../../../libstdc++-v3/libsupc++/vterminate.cc:95
#3  0x00007ffff7926c96 in __cxxabiv1::__terminate (handler=<optimized out>) at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:47
#4  0x00007ffff7926ce1 in std::terminate () at ../../../../libstdc++-v3/libsupc++/eh_terminate.cc:57
#5  0x00007ffff7926ef8 in __cxxabiv1::__cxa_throw (obj=0x629410, tinfo=0x7ffff7bb7830 <typeinfo for std::out_of_range>, dest=
    0x7ffff793b720 <std::out_of_range::~out_of_range()>) at ../../../../libstdc++-v3/libsupc++/eh_throw.cc:87
#6  0x00007ffff797d7c1 in std::__throw_out_of_range_fmt (
    __fmt=__fmt@entry=0x41d7e0 "%s: __pos (which is %zu) > this->size() (which is %zu)")
    at ../../../../../libstdc++-v3/src/c++11/functexcept.cc:101
#7  0x000000000040bc15 in _M_check (__s=0x41d7c7 "basic_string::substr", __pos=40, this=0x7fffffffd640)
    at /usr/include/c++/4.9.2/bits/basic_string.h:324
#8  substr (__n=8, __pos=40, this=0x7fffffffd640) at /usr/include/c++/4.9.2/bits/basic_string.h:2227
#9  libexercises::operator<< (out=..., exc=...) at qrz.cc:84
#10 0x000000000041ae95 in OnQrz () at qrz_exc.cc:78
#11 0x000000000040a4e5 in libmenu::Menu::show (this=this@entry=0x7fffffffda10) at menu.cc:179
#12 0x0000000000403618 in main () at main.cc:74

**Comment by DanielG** [comment]
I'm not the original author of this program, please report bugs over there: http://savannah.nongnu.org/bugs/?group=aldo
